# Generated by Django 3.0.8 on 2020-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='feature_to_home_page',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
