# Generated by Django 3.0.8 on 2020-10-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_feature_to_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='feature_to_home_page',
        ),
    ]
