# Generated by Django 3.0.8 on 2020-10-02 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0015_auto_20201002_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(related_name='product_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
