# Generated by Django 3.0.8 on 2020-10-02 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_auto_20201002_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_to_home_page',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='product_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
