# Generated by Django 3.0.8 on 2020-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201002_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alternative_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='image_alternative_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alternative_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
