# Generated by Django 3.0.8 on 2020-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201009_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flat_off_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
