# Generated by Django 3.0.8 on 2020-09-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contacted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
