# Generated by Django 3.0.8 on 2020-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_contacted_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
