# Generated by Django 3.0.8 on 2020-10-04 17:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fav_Icon', models.ImageField(upload_to='img/')),
                ('Site_Logo', models.ImageField(upload_to='img/')),
                ('FaceBook_Account', models.CharField(blank=True, max_length=255)),
                ('Twitter_Account', models.CharField(blank=True, max_length=255)),
                ('Instagram_Account', models.CharField(blank=True, max_length=255)),
                ('Linkdin_Account', models.CharField(blank=True, max_length=255)),
                ('Contact_No_1', models.CharField(blank=True, max_length=255)),
                ('Contact_No_2', models.CharField(blank=True, max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=255)),
                ('Short_About_Us', models.TextField(blank=True)),
                ('About_Us', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Our_Mission', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
