# Generated by Django 3.0.8 on 2020-10-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='Linkdin_Account',
            new_name='Linkedin_Account',
        ),
    ]
