# Generated by Django 3.0.8 on 2020-10-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201004_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Home_Page_Banner',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
