# Generated by Django 3.0.8 on 2020-10-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sitesetting_home_page_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Home_Page_Big_Text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='Home_Page_Small_Text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
