# Generated by Django 3.0.8 on 2020-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201005_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Home_Page_Banner_Alternative_Text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='Member_Profile_Alternative_Text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
