# Generated by Django 3.0.8 on 2020-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201009_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
