# Generated by Django 3.0.8 on 2020-10-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='positon_number',
            new_name='position_number',
        ),
    ]
