# Generated by Django 3.0.8 on 2020-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201013_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='faq_page_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='faq_page_meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
