# Generated by Django 3.0.8 on 2020-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201013_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_title', models.CharField(max_length=255)),
                ('account_page_title', models.CharField(max_length=255)),
                ('forget_page_title', models.CharField(max_length=255)),
                ('forget_comfirm_page_title', models.CharField(max_length=255)),
                ('change_password_page_title', models.CharField(max_length=255)),
                ('about_page_title', models.CharField(max_length=255)),
                ('contact_page_title', models.CharField(max_length=255)),
                ('faq_page_title', models.CharField(max_length=255)),
                ('error_404_page_title', models.CharField(max_length=255)),
                ('favourite_list_page_title', models.CharField(max_length=255)),
            ],
        ),
    ]
