# Generated by Django 5.1.6 on 2025-02-17 11:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('contacted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='answer')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fav_Icon', models.ImageField(upload_to='img/')),
                ('Site_Logo', models.ImageField(upload_to='img/')),
                ('home_page_title', models.CharField(blank=True, max_length=255)),
                ('account_page_title', models.CharField(blank=True, max_length=255)),
                ('forget_page_title', models.CharField(blank=True, max_length=255)),
                ('forget_comfirm_page_title', models.CharField(blank=True, max_length=255)),
                ('change_password_page_title', models.CharField(blank=True, max_length=255)),
                ('about_page_title', models.CharField(blank=True, max_length=255)),
                ('contact_page_title', models.CharField(blank=True, max_length=255)),
                ('faq_page_title', models.CharField(blank=True, max_length=255)),
                ('error_404_page_title', models.CharField(blank=True, max_length=255)),
                ('favourite_list_page_title', models.CharField(blank=True, max_length=255)),
                ('home_page_meta_description', models.TextField(blank=True, null=True)),
                ('home_page_meta_keywords', models.TextField(blank=True, null=True)),
                ('about_page_meta_description', models.TextField(blank=True, null=True)),
                ('about_page_meta_keywords', models.TextField(blank=True, null=True)),
                ('contact_page_meta_description', models.TextField(blank=True, null=True)),
                ('contact_page_meta_keywords', models.TextField(blank=True, null=True)),
                ('faq_page_meta_description', models.TextField(blank=True, null=True)),
                ('faq_page_meta_keywords', models.TextField(blank=True, null=True)),
                ('Home_Page_Banner', models.ImageField(blank=True, upload_to='img/')),
                ('Home_Page_Banner_Alternative_Text', models.CharField(blank=True, max_length=255)),
                ('Home_Page_Small_Text', models.CharField(blank=True, max_length=255)),
                ('Home_Page_Big_Text', models.CharField(blank=True, max_length=255)),
                ('FaceBook_Account', models.CharField(blank=True, max_length=255)),
                ('Twitter_Account', models.CharField(blank=True, max_length=255)),
                ('Instagram_Account', models.CharField(blank=True, max_length=255)),
                ('Linkedin_Account', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('Contact_No_1', models.CharField(blank=True, max_length=255)),
                ('Contact_No_2', models.CharField(blank=True, max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=255)),
                ('Short_About_Us', models.TextField(blank=True)),
                ('About_Us_Image', models.ImageField(blank=True, upload_to='img/')),
                ('About_Us_Image_Alternative_Text', models.CharField(blank=True, max_length=255)),
                ('About_Us', django_ckeditor_5.fields.CKEditor5Field(verbose_name='About_Us')),
                ('Our_Mission_Image', models.ImageField(blank=True, upload_to='img/')),
                ('Our_Mission_Image_Alternative_Text', models.CharField(blank=True, max_length=255)),
                ('Our_Mission', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Our_Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_Name', models.CharField(max_length=70)),
                ('Member_Position', models.CharField(max_length=100)),
                ('Member_Profile', models.ImageField(upload_to='img/')),
                ('Member_Profile_Alternative_Text', models.CharField(blank=True, max_length=255)),
                ('Member_FaceBook_Account', models.CharField(blank=True, max_length=255)),
                ('Member_Twitter_Account', models.CharField(blank=True, max_length=255)),
                ('Member_Instagram_Account', models.CharField(blank=True, max_length=255)),
                ('Member_Linkdin_Account', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
